#!/bin/sh

grep -q "^vhba " /proc/modules || exit 1

OPTIONS=
NUM_DEVICES=
AUDIO=
AUDIO_DEVICE=

[ -f /etc/sysconfig/cdemud ] && . /etc/sysconfig/cdemud
[ -f "$HOME/.cdemud-options" ] && . "$HOME/.cdemud-options"

[ -n "$NUM_DEVICES" ] && OPTIONS="$OPTIONS -n $NUM_DEVICES"
[ -n "$AUDIO" ] && OPTIONS="$OPTIONS -a $AUDIO"
[ -n "$AUDIO_DEVICE" ] && OPTIONS="$OPTIONS -o $AUDIO_DEVICE"

exec cdemud $OPTIONS
